// <auto-generated />
namespace VehicleRequisitionSystem.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class tblAssignedRequest_DriverIdRemoved_EmployeeIdAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tblAssignedRequest_DriverIdRemoved_EmployeeIdAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201809050337012_tblAssignedRequest_DriverIdRemoved_EmployeeIdAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
