// <auto-generated />
namespace VehicleRequisitionSystem.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class tblComments_RequestId_Description_Required : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tblComments_RequestId_Description_Required));
        
        string IMigrationMetadata.Id
        {
            get { return "201809090830200_tblComments_RequestId_Description_Required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
