// <auto-generated />
namespace VehicleRequisitionSystem.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class tblVehicleStatus_EmployeeId_Added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tblVehicleStatus_EmployeeId_Added));
        
        string IMigrationMetadata.Id
        {
            get { return "201809091839512_tblVehicleStatus_EmployeeId_Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
