// <auto-generated />
namespace VehicleRequisitionSystem.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class tblComments_UserId_DateTime_Added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tblComments_UserId_DateTime_Added));
        
        string IMigrationMetadata.Id
        {
            get { return "201809090935324_tblComments_UserId_DateTime_Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
