// <auto-generated />
namespace VehicleRequisitionSystem.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class tblRequest_AssignedRequisitionId_Removed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tblRequest_AssignedRequisitionId_Removed));
        
        string IMigrationMetadata.Id
        {
            get { return "201809030421201_tblRequest_AssignedRequisitionId_Removed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
