// <auto-generated />
namespace VehicleRequisitionSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RequisitionRequest_IsCanceled_Introduce : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RequisitionRequest_IsCanceled_Introduce));
        
        string IMigrationMetadata.Id
        {
            get { return "201806281641289_RequisitionRequest_IsCanceled_Introduce"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
