// <auto-generated />
namespace VehicleRequisitionSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserId_PropertyAdded_To_RequisitionRequestTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserId_PropertyAdded_To_RequisitionRequestTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201806270832209_UserId_PropertyAdded_To_RequisitionRequestTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
