// <auto-generated />
namespace VehicleRequisitionSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class string_No_to_VehicleTblAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(string_No_to_VehicleTblAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201806291736363_string_No_to_VehicleTblAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
