// <auto-generated />
namespace VehicleRequisitionSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RequisitionRequestTable_Modified : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RequisitionRequestTable_Modified));
        
        string IMigrationMetadata.Id
        {
            get { return "201806300822343_RequisitionRequestTable_Modified"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
